import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";


export const metadata: Metadata = {
  title: "ChatGpt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <SideBar/>
          {/* {Sidebar} */}
          {/* client provider-Notification */}
     <div className=" bg-[#343541] flex-1 ">
     {children}
     </div>
        </div>
      </body>
    </html>
  );
}
