import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import { SessionProvider } from "./components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "../../pages/api/auth/[...nextauth]";
import Login from "./components/Login";


export const metadata: Metadata = {
  title: "ChatGpt",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{


const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ?(
            <Login/>
          ):(
        <div className="flex">
          <div className="bg-[#202123] max-2-xs h-screen overflow-y-auto md:min-w-[20rem]">
          <SideBar/>

          </div>
          {/* {Sidebar} */}
          {/* client provider-Notification */}
     <div className=" bg-[#343541] flex-1 ">
     {children}
     </div>
        </div>
      )}
        </SessionProvider>
      </body>
    </html>
  );
}
